services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env.docker
    volumes:
      - pg_db:/var/lib/postgresql/data

  app:
    container_name: app
    build: back-end/
    image: app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env.docker
      
  app_react:
    build: ./front-end
    container_name: app_react
    image: app_react
    env_file:
      - front-end/.env.docker
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - app
      - app_react


volumes:
  build_react:
  pg_db: